# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contacts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'contacts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ontacts.proto\x12\x0f\x63omposelearning\"v\n\x07\x43ontact\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12#\n\x04role\x18\x05 \x01(\x0e\x32\x15.composelearning.Role\x12\x0e\n\x06\x61\x63tive\x18\x06 \x01(\x08\"9\n\x0b\x43ontactList\x12*\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x18.composelearning.Contact*E\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\x0c\n\x08\x45NGINEER\x10\x01\x12\x0c\n\x08\x44\x45SIGNER\x10\x02\x12\x0b\n\x07MANAGER\x10\x03\x42%\n!com.example.composelearning.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contacts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.example.composelearning.protoP\001'
  _globals['_ROLE']._serialized_start=214
  _globals['_ROLE']._serialized_end=283
  _globals['_CONTACT']._serialized_start=35
  _globals['_CONTACT']._serialized_end=153
  _globals['_CONTACTLIST']._serialized_start=155
  _globals['_CONTACTLIST']._serialized_end=212
# @@protoc_insertion_point(module_scope)
